### ISSUE TITLE
Release liboxen on crates.io

### ISSUE THREAD

**Issue by Jasper-Bekkers** [Oxen-AI/oxen-archive#100]
Would you be so kind to create a crate for this and publish it on crates.io?

**Comment by gschoeni** [comment]
Yes, added to backlog and will let you know when it's up there!

**Comment by Jasper-Bekkers** [comment]
Fwiw for our crates we're quite happy with cargo-release to help do the releases, really streamlines some things

**Comment by gschoeni** [comment]
Sorry this took so long! But it is now released on crates.io. 

https://crates.io/crates/liboxen

Also working on a python wrapper that you can pip install as well if that is better in your workflow.

https://pypi.org/project/oxenai/
