### ISSUE TITLE
Error when opening files usign the platform

### ISSUE THREAD

**Issue by luanmuniz** [Oxen-AI/oxen-archive#112]
The image and the links are self-explanatory.

<img width="732" alt="Screenshot 2023-03-14 at 12 52 09" src="https://user-images.githubusercontent.com/3428149/225059534-4f35fcf8-0e98-4090-92bd-2ccff7e3533c.png">

https://www.oxen.ai/luanmuniz/cvm/file/main/data/ADM_CART/CAD/DADOS/cad_adm_cart/cad_adm_cart_diretor.csv

It seems every CSV file has that issue.

**Comment by gschoeni** [comment]
Looks like this csv uses ';' as a delimiter and we are assuming ','

Adding a ticket to see if we can automatically detect the delimiter, or at least be able to provide it as metadata

**Comment by gschoeni** [comment]
Backend now tries to auto-detect the delimiter, you can also override the delimiter with an API or command line param. Tested on the data provided above. There is also utf-8 encoding errors in the data above, so switched to a more lossy parser that will replace invalid UTF-8 with ?.

**Comment by luanmuniz** [comment]
It still doesn't seem to be parsed correctly, but at least it's not giving an error now!
