### ISSUE TITLE
New 'info' sub command

### ISSUE THREAD

**Issue by paul-hammant** [Oxen-AI/oxen-archive#138]
If I add then commit a file, I can see in the console that hash was calculated for the commit.   I can't see from the command line to conjure up that hash again.  `oxen info <resource-path>` would be a great addition to see the hash and other oxen-centric meta info for the same resource.

Related, `oxen log <resource-path>` would be nice place for a subset of commits that affected that named resource.

**Comment by gschoeni** [comment]
Thanks for the thoughts @paul-hammant! We're looking into adding the `oxen info` command now, we will expose the hash, the extracted data type, and other metadata oxen can detect about the file. 

`oxen log <resource-path>` is also super interesting. Adding to the backlog

**Comment by gschoeni** [comment]
Added the `oxen info` subcommand in release 0.6.6, more info here: https://github.com/Oxen-AI/oxen-release#content-hashing-and-core-metadata-extraction

**Comment by paul-hammant** [comment]
Fantastic!
