### ISSUE TITLE
`oxen add` fails with memory allocation error

### ISSUE THREAD

**Issue by rainiwu** [Oxen-AI/oxen-archive#244]
Hi, 

I have a large dataset I want to track with Oxen. I installed the CLI tool from source (43c8a9bdfd4d923ca069378cd764676da1f303c2) using `cargo install --path .`. Following the instructions from the [documentation](https://docs.oxen.ai/getting-started/intro), I successfully ran `oxen init` in the folder with my dataset, but `oxen add` fails with:

```bash
$> oxen add <data_file>
memory allocation of <size_of_data_file> bytes failed
Aborted (core dumped)
```

The computer I am using to run `oxen` has a memory capacity smaller than the size of the file I want to track. Is this the expected behavior?

Thanks in advance!

**Comment by gschoeni** [comment]
Great call out! Looks like our hashing algorithm implementation was loading the entire file into memory in order to hash. We updated it to a streaming hash in #246 and testing it out now 🚀

**Comment by rainiwu** [comment]
Wow that's a quick turnaround! I've installed the latest version and `oxen add` works for me now, cheers!
