### ISSUE TITLE
I can ls remote repo but can't use Python API to do the samething.

### ISSUE THREAD

**Issue by NoahAmethyst** [Oxen-AI/oxen-archive#271]
I deployed oxen server in my own server machine and try to get remote repo's directry and files.

Here's what i input and response:
<img width="711" alt="image" src="https://github.com/Oxen-AI/Oxen/assets/46391031/612fbd07-056f-46a6-9045-af790b2b3f2d">

<img width="704" alt="image" src="https://github.com/Oxen-AI/Oxen/assets/46391031/6d70a1fb-fdd1-462a-8fbc-d41aa8bba55f">

But when i use python API like this:
```python
    remote_repo = oxen.RemoteRepo(repo_id, local_host, revision='origin', scheme='http')
    print(remote_repo.ls(''))
```

I got error:
`ValueError: Err: resource_not_found`

When i put `images` in the `ls` function  as first param the same error happened.

Any suggestions please tell me.

THX.

**Comment by benartuso** [comment]
@NoahAmethyst thanks for opening! 

I noticed that your `revision` param is being passed in as `origin`, which is our default remote name. This param should be a branch or commit id, not a remote name.

Are you still seeing the same error if you pass in 

```
remote_repo = oxen.RemoteRepo(repo_id, local_host, revision='main', scheme='http')
```

instead?

**Comment by NoahAmethyst** [comment]
> @NoahAmethyst thanks for opening!
> 
> I noticed that your `revision` param is being passed in as `origin`, which is our default remote name. This param should be a branch or commit id, not a remote name.
> 
> Are you still seeing the same error if you pass in
> 
> ```
> remote_repo = oxen.RemoteRepo(repo_id, local_host, revision='main', scheme='http')
> ```
> 
> instead?

That's worked！THX for your reponse!

**Comment by NoahAmethyst** [comment]
It's solved
