### ISSUE TITLE
`test_remote_merger_multiple_commits_conflict_head_is_ahead` fails on Windows |  Err: Corruption: Can't access /000076.sst

### ISSUE THREAD

**Issue by SamuelMarks** [Oxen-AI/oxen-archive#321]
Running on 8a9cca9

```
🎉 Push successful
Error running test. Err: Corruption: Can't access /000076.sst: IO error: No such file or directory: Can not get size for: data\test\runs\repo\data\test\runs\83c95c94-b848-4734-85ba-632fbdf06091\.oxen\staged\files\/000076.sst: The system cannot find the file specified.


thread 'api::remote::merger::tests::test_remote_merger_multiple_commits_conflict_head_is_ahead' panicked at src/lib/src\test.rs:380:5:
assertion failed: result
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    api::remote::merger::tests::test_remote_merger_multiple_commits_conflict_head_is_ahead

test result: FAILED. 437 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 6632.25s

error: test failed, to rerun pass `--lib`
````

**Comment by gschoeni** [comment]
Hey Samuel, thanks for flagging this! We are having some inconsistent behavior on windows unit tests. Looking at the file paths I assume you are on Windows? I feel like it might be a rocksdb access pattern we need to fix up. 

Can you consistently reproduce running the single test?

```
cargo test --lib name_of_test
```

Or is it a race condition when running them in parallel?

**Comment by SamuelMarks** [comment]
Good news, reran @ 448d691 with latest Rust [I always use latest Rust and MSVC] and no further issues.

BTW: Yes I was running with `--test-threads=1` before. Takes forever!

Thanks for following up

**Comment by gschoeni** [comment]
The speed of the tests is definitely a big bottleneck right now 😅 need to get creative on speeding them up
