### ISSUE TITLE
No `oxen schemas rm` command

### ISSUE THREAD

**Issue by Bit0r** [Oxen-AI/oxen-archive#362]
![image](https://github.com/Oxen-AI/Oxen/assets/43108543/14597fa4-4b55-43ac-8fe6-2c82da176383)

Has the recent update caused the `rm` subcommand of `oxen schemas` to be removed?

**Comment by gschoeni** [comment]
Yes, great catch. Looks like it got lost in the refactor. I just added it back in [here](https://github.com/Oxen-AI/Oxen/commit/96bd64dcef68015ed6e86e60031b3264d3ef462c). Will kick off a new release!
