### ISSUE TITLE
Enable Link-Time Optimization (LTO)

### ISSUE THREAD

**Issue by zamazan4ik** [Oxen-AI/oxen-archive#476]
Hi!

I noticed that Link-Time Optimization (LTO) is not enabled for Oxen. I suggest switching it on since it will reduce the binary size (always a good thing to have) and will likely improve the application's performance (its CPU part). If you want to read more about LTO, I can recommend starting from [this](https://doc.rust-lang.org/rustc/codegen-options/index.html#lto) Rustc documentation.

I suggest enabling LTO only for the Release builds so as not to sacrifice the developers' experience while working on the project since LTO consumes an additional amount of time to finish the compilation routine. If you think that a regular Release build should not be affected by such a change as well, then I suggest adding an additional `dist` or `release-lto` profile where in addition to regular `release` optimizations LTO will also be added. Such a change simplifies life for maintainers and others interested in the project persons who want to build the most performant version of the application. Using ThinLTO should also help to reduce the build-time overhead with LTO. E.g., check `cargo-outdated` Release [profile](https://github.com/kbknapp/cargo-outdated/blob/master/Cargo.toml#L48).

Basically, it can be enabled with the following lines:

```
[profile.release]
lto = true
```

I have made quick tests (Fedora 41, Rustc 1.82) by adding `lto = true` to the Release profile. The binary size reduction is the following:
* `oxen`: from 103 Mib to 99 Mib
* `oxen-server`: from 107 to 103 Mib

Additionally, I performed a similar test for https://github.com/Oxen-AI/oxen-release/ project, where the shared library (`liboxen.so`) size reduction was from 124 Mib to 105 Mib so LTO would be useful for this Python package too.

Thank you.

**Comment by gschoeni** [comment]
This is great, thanks for the pointer! We will add it to the next release build.

**Comment by gschoeni** [comment]
Added this here: https://github.com/Oxen-AI/Oxen/commit/d39148b77eebbf27fb128d131d257308dcee0670

**Comment by zamazan4ik** [comment]
@gschoeni thanks a lot!

A very quick question - does your fix enable LTO for https://github.com/Oxen-AI/oxen-release/ too?

**Comment by gschoeni** [comment]
Yep! I did it on this commit for `oxen-release`

https://github.com/Oxen-AI/oxen-release/commit/56515d0d03288cf961374ea2787035c816d371a6
