### ISSUE TITLE
oxen: Bad CPU type in executable

### ISSUE THREAD

**Issue by paul-hammant** [Oxen-AI/oxen-archive#90]
Oxen installed on my i5 MacMini from 2018 via homebrew, then `oxen init` yields:

`oxen: Bad CPU type in executable`

Seems there's advice online as to how Apple silicon users may encounter this in the transition years (https://medium.com/@jithmisha/fix-for-macbook-air-m1-m2-bad-cpu-type-in-executable-error-3719a0a1cb6), but not much advice on legacy ARM64 users now transition is in the past.

**Comment by paul-hammant** [comment]
`cargo build` after a Git clone, makes an exe for me that doesn't have the bad-CPU warning.

**Comment by gschoeni** [comment]
Thanks for the link! We're adding some more OSX builds to our CI pipeline, will have in the next homebrew release

**Comment by gschoeni** [comment]
Added builds for x86_64 and OSX 11,12,13 to homebrew install
