### ISSUE TITLE
issue with display of files on oxen.ai website

### ISSUE THREAD

**Issue by n8fr8** [Oxen-AI/oxen-archive#97]
First, great idea, solid implementation, excellent work. We've been in need of something like this for our proofmode.org project.

I just successfully installed, configured, and published a few folders of media+data to oxen.ai. 

However, when I view this folder on the website, it seems empty:
https://www.oxen.ai/proofmode/baseline/dir/main/Roland/2023-02-04%20Big%20Bay%20Surfers

Is this just a UX issue? If someone else clones the repo, will they see all of the individual files?

**Comment by gschoeni** [comment]
@n8fr8 appreciate it! 

Looking into the issue. I do believe it is a UX issue, because I cloned your repo and was able to see the files locally. Looking into the web hub side of things now, but will leave open until we confirm it's not an API issue.

**Comment by gschoeni** [comment]
@n8fr8 This was an issue with our UI and not the core Oxen server, rolling out a fix to prod now.

**Comment by n8fr8** [comment]
Working great now. Thanks!
